### ISSUE TITLE
`Moralis.Streams.parsedLogs()` breaks when using contracts calling another contracts.

### ISSUE THREAD

**Issue by 0xch** [MoralisWeb3/Moralis-JS-SDK#1076]
### Checklist
- [ x ] I am not disclosing a [vulnerability](https://github.com/MoralisWeb3/Moralis-JS-SDK/blob/main/SECURITY.md).
- [ x ] I have searched through [existing issues](https://github.com/MoralisWeb3/Moralis-JS-SDK/issues?q=is%3Aissue) and the [Moralis Forum](https://forum.moralis.io/).
- [ x ] I can reproduce the issue with the [latest SDK release](https://github.com/MoralisWeb3/Moralis-JS-SDK/releases), and my server is updated to the latest version.

### Issue Description
Method `Moralis.Streams.parsedLogs()` is trying to parse all events, but in case of missing any of the events in the given ABI is throws an Error.
This behaviour makes almost impossible to decode contracts calling other contracts because other contracts' ABI might be different than current contract's ABI.

There is a way workaround it, it's by receiving only contract's logs by:
```
    includeContractLogs: true,
    includeNativeTxs: false,
    includeAllTxLogs: false,
    includeInternalTxs: false,
```
But in case user wish to receive more logs it's a problem.

### Steps + code to reproduce
Code with this case:
```
import Moralis from 'moralis';

const test = async () => {
    const webhookData =  {
            confirmed: true,
            chainId: '0x61',
            abi: [{
                "anonymous": false,
                "inputs": [{
                    "indexed": false,
                    "internalType": "uint256",
                    "name": "offerId",
                    "type": "uint256"
                }, {
                    "indexed": false,
                    "internalType": "contract ISafeTransfer",
                    "name": "nftContractAddress",
                    "type": "address"
                }, {"indexed": false, "internalType": "address", "name": "owner", "type": "address"}, {
                    "indexed": false,
                    "internalType": "uint128",
                    "name": "price",
                    "type": "uint128"
                }, {"indexed": false, "internalType": "uint32", "name": "assetId", "type": "uint32"}, {
                    "indexed": false,
                    "internalType": "uint32",
                    "name": "amount",
                    "type": "uint32"
                }, {"indexed": false, "internalType": "uint8", "name": "contractType", "type": "uint8"}],
                "name": "OfferCreated",
                "type": "event"
            }],
            streamId: '752d044d-75aa-4bb7-8dbf-80609f19d3a4',
            tag: 'OfferCreated',
            retries: 0,
            block: {
                number: '28441615',
                hash: '0x4460aa1b8d3d6638b74b1e0f03c6f927073e27ae793f43a14af3da1d431ad23a',
                timestamp: '1680015651'
            },
            logs: [
                {
                    logIndex: '3',
                    transactionHash: '0x71b1af6b108b36277265940f99351b0e6a44c8d4bf94fce7cb8f51394a1fe5af',
                    address: '0x00000ffcb5e13055e7651246494bb87e80b8925d',
                    data: '0x0000000000000000000000000000000000000000000000000000000000000056000000000000000000000000359e746ce5ffb0edb3220cfa2d37f6de52f48be10000000000000000000000008618682bcfba38b9ffee8247bbed9d61f5579be6000000000000000000000000000000000000000000003f870857a3e0e380000000000000000000000000000000000000000000000000000000000000000000d700000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000001',
                    topic0: '0x7d91ee6f5d1c8d8d319ffdd920d7b5c4b44a4f3a7741ccf2fd1b62b09756c214',
                    topic1: null,
                    topic2: null,
                    topic3: null
                },
                {
                    logIndex: '1',
                    transactionHash: '0x71b1af6b108b36277265940f99351b0e6a44c8d4bf94fce7cb8f51394a1fe5af',
                    address: '0x000006ce5ffb0edb3220cfa2d37f6de52f48be1',
                    data: '0x',
                    topic0: '0x8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925',
                    topic1: '0x0000000000000000000000008618682bcfba38b9ffee8247bbed9d61f5579be6',
                    topic2: '0x0000000000000000000000000000000000000000000000000000000000000000',
                    topic3: '0x00000000000000000000000000000000000000000000000000000000000000d7'
                },
                {
                    logIndex: '2',
                    transactionHash: '0x71b1af6b108b36277265940f99351b0e6a44c8d4bf94fce7cb8f51394a1fe5af',
                    address: '0x000006ce5ffb0edb3220cfa2d37f6de52f48be1',
                    data: '0x',
                    topic0: '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
                    topic1: '0x0000000000000000000000008618682bcfba38b9ffee8247bbed9d61f5579be6',
                    topic2: '0x00000000000000000000000033e6effcb5e13055e7651246494bb87e80b8925d',
                    topic3: '0x00000000000000000000000000000000000000000000000000000000000000d7'
                }
            ],
            txs: [],
            txsInternal: [],
            erc20Transfers: [],
            erc20Approvals: [],
            nftTokenApprovals: [],
            nftApprovals: { ERC721: [ [] ], ERC1155: [] },
            nftTransfers: [],
            nativeBalances: []
        }
    ;

    const decodedLogs = Moralis.Streams.parsedLogs(webhookData);
    console.log(decodedLogs);
};

test();
```

### Actual Outcome
Lib throws an Error

### Expected Outcome
Lib displays decoded data only for events in ABI. For non-existing events leave not decoded content.

### Environment

Server:
Newest version - `Moralis@2.18.0`

### Logs
```
Error: no matching event (argument="topichash", value="0x...", code=INVALID_ARGUMENT, version=abi/5.7.0)
    at Logger.throwError (/var/www/node_modules/@ethersproject/logger/lib/index.js:247:20)
    at Logger.throwArgumentError (/var/www/node_modules/@ethersproject/logger/lib/index.js:250:21)
    at Interface.getEvent (/var/www/node_modules/@ethersproject/abi/lib/interface.js:216:20)
    at LogParser.read (file:///var/www/node_modules/@moralisweb3/streams/lib/esm/index.js:578:47)
    at file:///var/www/node_modules/@moralisweb3/streams/lib/esm/index.js:789:41
    at Array.forEach (<anonymous>)
    at parseLog (file:///var/www/node_modules/@moralisweb3/streams/lib/esm/index.js:788:10)
    at Streams._this.parsedLogs (file:///var/www/node_modules/@moralisweb3/streams/lib/esm/index.js:903:60)
    at test (file:///var/www/others/moralis-cloud/streams/d.js:88:41) {
  reason: 'no matching event',
  code: 'INVALID_ARGUMENT',
  argument: 'topichash',
  value: '0x...'
```

**Comment by b4rtaz** [comment]
Hi @0xch!

To solve this problem you may join ABIs from two contracts and set that to the custom ABI field during the stream creation.

![image](https://user-images.githubusercontent.com/12797776/228514363-a33b5f71-24b1-4303-ad42-116bf3ad7895.png)

```json
[{
        "anonymous": false,
        "inputs": [{
            "indexed": false,
            "internalType": "uint256",
            "name": "offerId",
            "type": "uint256"
        }, {
            "indexed": false,
            "internalType": "contract ISafeTransfer",
            "name": "nftContractAddress",
            "type": "address"
        }, {"indexed": false, "internalType": "address", "name": "owner", "type": "address"}, {
            "indexed": false,
            "internalType": "uint128",
            "name": "price",
            "type": "uint128"
        }, {"indexed": false, "internalType": "uint32", "name": "assetId", "type": "uint32"}, {
            "indexed": false,
            "internalType": "uint32",
            "name": "amount",
            "type": "uint32"
        }, {"indexed": false, "internalType": "uint8", "name": "contractType", "type": "uint8"}],
        "name": "OfferCreated",
        "type": "event"
    },
    {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"owner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"approved",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"uint256",
            "name":"tokenId",
            "type":"uint256"
         }
      ],
      "name":"Approval",
      "type":"event"
   },
   {
    "anonymous":false,
    "inputs":[
       {
          "indexed":true,
          "internalType":"address",
          "name":"from",
          "type":"address"
       },
       {
          "indexed":true,
          "internalType":"address",
          "name":"to",
          "type":"address"
       },
       {
          "indexed":true,
          "internalType":"uint256",
          "name":"tokenId",
          "type":"uint256"
       }
    ],
    "name":"Transfer",
    "type":"event"
 }]
```

**Comment by 0xch** [comment]
I see, thanks
